// Generated by CoffeeScript 1.10.0
(function() {
  (function() {
    var MainController;
    MainController = function() {
      this.input = "Google.Color.Generator";
      this.colorStyles = ['blue', 'red', 'yellow', 'blue', 'green', 'red'];
      this.texts = (function(_this) {
        return function(input) {
          if (input == null) {
            return [];
          }
          return input.split('');
        };
      })(this);
      this.getColorClass = function(index) {
        return this.colorStyles[index % 4];
      };
    };
    return angular.module("googleColorGenerator", ["ngRoute"]).controller("MainController", MainController);
  })();

}).call(this);
